### ISSUE TITLE
Add new labels

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/odd-process-workflow#1]
@annieszot commented on [Tue Mar 12 2019](https://github.com/cityofaustin/techstack/issues/1462)

Add to techstack labels: journey map, consult, database, workshop, statement of work, scoring, blueprint, and evaluation
https://github.com/cityofaustin/techstack/labels?page=4&sort=name-asc

- [ ] Learn how to add labels
- [ ] Define labels
- [ ] Start adding labels to issues

**Comment by majette8** [comment]
added labels outlined by Annie.
