### ISSUE TITLE
Set Office Hours structure for SDL (and alpha?) 

### ISSUE THREAD

**Issue by majette8** [cityofaustin/odd-process-workflow#16]

**Comment by srigdon** [comment]
To-do list for this task: 

- [x] Research how other service design labs, innovation offices, and perhaps design firms do office hours. NYC's resources, for example: https://www1.nyc.gov/site/opportunity/portfolio/service-design-studio.page 
- [x] Draft an office hours structure: what services and types of help do we offer, who can attend, how do people sign up, how to message office hours, what resources we need, how much time we estimate will need to be dedicated to this, what's the purpose of office hours. 
- [x] Share draft with team, ask for feedback for at least two weeks (but maybe two sprints?) and remind people about it at least weekly.

**Comment by srigdon** [comment]
Draft office hours description and research doc: https://docs.google.com/document/d/1DFFm1P58UfDeytl5hQUMQXmy2uqchs8sK4jrgvAhbJ8/edit
