### ISSUE TITLE
Evaluate Current journey maps

### ISSUE THREAD

**Issue by majette8** [cityofaustin/odd-process-workflow#3]

**Comment by stephaniegates** [comment]
@ChristopherLuedtke Is this to map our internal process including what we hand off to content and alpha?

**Comment by ChristopherLuedtke** [comment]
Yes- This is part of our internal process, and the evidence we are creating to documents current/future process from intake-pass off- close.

**Comment by majette8** [comment]
3/22/19 - process flow mapping with Sarah Rigdon
3/25/19 - process flow mapping with Laura T
3/25/19 - process flow mapping with Taylor C
3/26/19 - process flow mapping with Tori B and Chase C
3/28/19 - process flow mapping with Desi R and Chris L
