### ISSUE TITLE
Develop current org chart with decision flow

### ISSUE THREAD

**Issue by majette8** [cityofaustin/odd-process-workflow#4]

**Comment by annieszot** [comment]
https://docs.google.com/presentation/d/1TMTSDsoqRbBanlLROqjuNRIai9vUj_fL4S048WyaFYA/edit?usp=sharing Potential user stories for journey map

**Comment by majette8** [comment]
link to job titles and descriptions - some are no longer relevant but this can give us a start
https://github.com/cityofaustin/odd/tree/master/_jobs/positions

**Comment by majette8** [comment]
3/27/19 - org chart meeting with Gerald O. 
3/28/19 - org chart meeting with Marni W.
