### ISSUE TITLE
Scoping Criteria document

### ISSUE THREAD

**Issue by majette8** [cityofaustin/odd-process-workflow#5]
Develop a document that outlines the key requests, business needs, budget constraints, etc

**Comment by majette8** [comment]
here is a template that we may be able to draw inspiration from. I think it was used for the original Fellows program. 
[https://docs.google.com/document/d/1vDxC2RGlArTBOQ5fVGVeJ2LdY-bYIECPKgMqjv9F5jQ/edit?usp=sharing](url)

**Comment by annieszot** [comment]
Draft started
https://docs.google.com/document/d/1Cw2TdsxKZkmXL-ys6n1SKhvCA9iHvRXyWKhPBWdU4ag/edit#
Adding @srigdon to form a "Think Tank" for the scoping criteria

**Comment by annieszot** [comment]
Shared with @majette8 and @srigdon for review

**Comment by annieszot** [comment]
@majette8 Can you please add this doc to the Google drive ODD Workflow Process folder? I don't have permission to "edit" the folder

**Comment by annieszot** [comment]
@srigdon reviewed, removing assignee

**Comment by annieszot** [comment]
https://docs.google.com/document/d/1Cw2TdsxKZkmXL-ys6n1SKhvCA9iHvRXyWKhPBWdU4ag/edit#
Adding @stephaniegates and @danielhonker to look at before next sprint (April 3).

**Comment by annieszot** [comment]
- [x] Refer to https://docs.google.com/document/d/1cunuLVHXqowwVBxvgYERwRJtpO2sxnXyRF3Vvvvl-bQ/edit#

**Comment by annieszot** [comment]
Per conversation with @majette8, will seek approval from team, Marni for Sprint 2 (Wed. 4/17) then user test the scope criteria doc for Sprint 3 (Thurs. 4/18-Wed. 5/1)

**Comment by annieszot** [comment]
Documentation on feedback from Marni: 
- [x] Make sure capture both deliverables and outcome --reword section 1.2
- [x] Edit wording on 1.4 Measuring success - "how are we testing?" 
- [x] For communications expectations, specify "these are our policies..."
- [ ] How will info. be collected? 
- [ ] Document user testing #37

**Comment by annieszot** [comment]
The document will not be tested but revised iteratively. 
Assigning wordsmithing from @majette8 on "Create and Impact"
Asking @srigdon for change management recommendations
Requested due date to wrap and close issue Tuesday, April 30
Revised doc: https://docs.google.com/document/d/1Cw2TdsxKZkmXL-ys6n1SKhvCA9iHvRXyWKhPBWdU4ag/edit#

**Comment by majette8** [comment]
Made minor wordSmithing edit
