### ISSUE TITLE
Intake Form Development

### ISSUE THREAD

**Issue by majette8** [cityofaustin/odd-process-workflow#7]
Possible items on form: checklist to ensure clients don’t miss anything
Decision needs to be made on keeping form private vs public 

Possible other team members: Tori B

**Comment by majette8** [comment]
this is an old form.  I wonder is this can be a good reference point 
[https://airtable.com/shrbF5MtsBHC8hPBv](url)

**Comment by annieszot** [comment]
https://docs.google.com/document/d/1cunuLVHXqowwVBxvgYERwRJtpO2sxnXyRF3Vvvvl-bQ/edit#

**Comment by majette8** [comment]
Incorporated feedback from Ben and Marni (5/3/2019)
